### ISSUE TITLE
Change PROJECT_NUMBER and SERVICE_ID to audience

### ISSUE THREAD

**Issue by janmasarik** [kiwicom/js-iam-middleware#90]
It's simpler to have 1 config value with the whole string instead of creating audience from 2 values in the code https://github.com/kiwicom/js-iam-middleware/pull/88/files#diff-b7fae9f38acbdf93aa1babe55dc76e95R25

Backwards compatibility would be nice, but not required since there are very few users.

**Comment by bayotop** [comment]
Done in https://github.com/kiwicom/js-iam-middleware/pull/106.
